#version: 2.1
#orbs:
#  python: circleci/python@2.0.3
#  heroku: circleci/heroku@1.2.6
#
#jobs:
#  build_and_test:
#    executor: python/default
#    steps:
#      - checkout
#      - python/install-packages:
#          pkg-manager: pip
#      - run:
#          name: Run tests
#          command: python -m unittest tests_diary
#      - persist_to_workspace:
#          root: ~/project
#          paths:
#            - .
#
#  deploy:
#    executor: python/default
#    steps:
#      - attach_workspace:
#          at: ~/project
#      - heroku/deploy-via-git:
#          force: true
#
#workflows:
#  test_my_app:
#    jobs:
#      - build_and_test
#      - deploy:
#          requires:
#            - build_and_test
#          filters:
#            branches:
#              only: main

version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run Tests with Coverage
          command: |
            coverage run -m unittest discover

      - run:
          name: Upload Coverage to Coveralls
          command: |
            coveralls
